FRAMEWORKS = {
    "GDPR": {
        "name": "GDPR",
        "description": "EU General Data Protection Regulation — applies to any company handling EU residents' personal data.",
        "requirements": [
            {"id": "GDPR-1",  "name": "Identity of data controller",           "description": "The document must name the company responsible for processing personal data and provide contact details."},
            {"id": "GDPR-2",  "name": "Data Protection Officer contact",        "description": "If a DPO is appointed, their contact details must be disclosed."},
            {"id": "GDPR-3",  "name": "Purposes and legal basis for processing","description": "Must state why data is collected and the legal basis (consent, contract, legitimate interest, etc.)."},
            {"id": "GDPR-4",  "name": "Recipients of personal data",            "description": "Must name or describe categories of third parties who receive personal data."},
            {"id": "GDPR-5",  "name": "Data retention period",                  "description": "Must state how long personal data is kept before deletion."},
            {"id": "GDPR-6",  "name": "Right to access",                        "description": "Must inform individuals of their right to obtain a copy of their personal data."},
            {"id": "GDPR-7",  "name": "Right to rectification",                 "description": "Must inform individuals of their right to correct inaccurate personal data."},
            {"id": "GDPR-8",  "name": "Right to erasure",                       "description": "Must inform individuals of their right to request deletion of their data."},
            {"id": "GDPR-9",  "name": "Right to withdraw consent",              "description": "Must explain how individuals can withdraw consent at any time."},
            {"id": "GDPR-10", "name": "Right to lodge a complaint",             "description": "Must inform individuals of their right to complain to a supervisory authority (e.g. ICO, CNIL)."},
        ],
    },
    "SOC2": {
        "name": "SOC 2",
        "description": "AICPA Trust Services Criteria — a voluntary security certification required by enterprise customers of SaaS and cloud providers.",
        "requirements": [
            {"id": "SOC2-1",  "name": "Security policy and access control",     "description": "Must document security policies governing who can access systems and how access is granted and revoked."},
            {"id": "SOC2-2",  "name": "Encryption in transit and at rest",      "description": "Must state that data is encrypted with TLS/HTTPS in transit and AES-256 (or equivalent) at rest."},
            {"id": "SOC2-3",  "name": "Availability and uptime commitments",    "description": "Must disclose an uptime SLA (e.g. 99.9%) and describe redundancy or failover mechanisms."},
            {"id": "SOC2-4",  "name": "Incident response procedures",           "description": "Must describe the process for detecting, containing, and notifying customers of security incidents."},
            {"id": "SOC2-5",  "name": "Vendor and third-party risk management", "description": "Must state that third-party vendors are assessed for security compliance before and during engagement."},
            {"id": "SOC2-6",  "name": "Audit logging and monitoring",           "description": "Must confirm that system activity is logged and actively monitored for anomalies."},
            {"id": "SOC2-7",  "name": "Change management procedures",           "description": "Must describe processes for testing and approving code/infrastructure changes before production deployment."},
            {"id": "SOC2-8",  "name": "Business continuity and disaster recovery","description": "Must describe backup procedures and recovery time/point objectives (RTO/RPO) after a major incident."},
            {"id": "SOC2-9",  "name": "Employee security training",             "description": "Must state that employees receive security awareness training and undergo background screening."},
            {"id": "SOC2-10", "name": "Penetration testing and vulnerability management","description": "Must state that regular penetration tests and vulnerability scans are conducted."},
        ],
    },
    "HIPAA": {
        "name": "HIPAA",
        "description": "US Health Insurance Portability and Accountability Act — applies to entities handling Protected Health Information (PHI).",
        "requirements": [
            {"id": "HIPAA-1",  "name": "Notice of Privacy Practices",           "description": "Covered entities must provide patients with a written notice describing how PHI is used and disclosed."},
            {"id": "HIPAA-2",  "name": "PHI use and disclosure description",    "description": "Must explain the specific ways patient health data is used (treatment, payment, healthcare operations)."},
            {"id": "HIPAA-3",  "name": "Patient rights regarding PHI",          "description": "Must explain the patient's right to access, copy, and request amendments to their health records."},
            {"id": "HIPAA-4",  "name": "Minimum necessary standard",            "description": "Must state that only the minimum necessary PHI is accessed or shared for any given purpose."},
            {"id": "HIPAA-5",  "name": "Business Associate Agreements",         "description": "Must disclose that any third-party vendor handling PHI has signed a Business Associate Agreement (BAA)."},
            {"id": "HIPAA-6",  "name": "Security safeguards for PHI",           "description": "Must describe administrative, physical, and technical safeguards protecting health data."},
            {"id": "HIPAA-7",  "name": "Breach notification policy",            "description": "Must state the obligation to notify patients and HHS within 60 days of a PHI data breach."},
            {"id": "HIPAA-8",  "name": "Right to request PHI restrictions",     "description": "Must acknowledge that patients can request restrictions on how their health information is used."},
            {"id": "HIPAA-9",  "name": "Workforce training and access controls","description": "Must state that staff are trained on HIPAA requirements and that PHI access is role-based."},
            {"id": "HIPAA-10", "name": "PHI record retention (6-year minimum)", "description": "Must confirm that PHI and related documentation is retained for at least 6 years."},
        ],
    },
    "ISO27001": {
        "name": "ISO 27001",
        "description": "International standard for information security management systems (ISMS) — adopted by enterprises and government contractors globally.",
        "requirements": [
            {"id": "ISO-1",  "name": "Information security policy",             "description": "Must document a formal information security policy approved by management and communicated to all staff."},
            {"id": "ISO-2",  "name": "Risk assessment and treatment",           "description": "Must describe a systematic process for identifying, evaluating, and treating information security risks."},
            {"id": "ISO-3",  "name": "Asset management",                        "description": "Must maintain an inventory of information assets and assign clear ownership responsibilities."},
            {"id": "ISO-4",  "name": "Access control policy",                   "description": "Must define access control rules based on business and security requirements, applying least privilege."},
            {"id": "ISO-5",  "name": "Cryptography policy",                     "description": "Must define rules for using cryptographic controls to protect information confidentiality and integrity."},
            {"id": "ISO-6",  "name": "Physical and environmental security",     "description": "Must describe controls preventing unauthorized physical access to data processing facilities."},
            {"id": "ISO-7",  "name": "Operations security",                     "description": "Must document operational procedures for IT systems including capacity, change, and malware protection."},
            {"id": "ISO-8",  "name": "Incident management",                     "description": "Must define responsibilities and procedures for managing security incidents and reporting weaknesses."},
            {"id": "ISO-9",  "name": "Business continuity management",          "description": "Must describe how information security continuity is planned and maintained during adverse situations."},
            {"id": "ISO-10", "name": "Compliance and audit",                    "description": "Must demonstrate compliance with legal requirements and conduct regular internal security audits."},
        ],
    },
}

FRAMEWORK_DESCRIPTIONS = {key: fw["description"] for key, fw in FRAMEWORKS.items()}