from datetime import datetime


def generate_report(url: str, framework: str, audit_result: dict) -> str:
    """
    Turns the raw audit_result dict into a clean, readable report string.
    This is what gets printed to the terminal during the demo.

    No LLM needed here — just Python string formatting.
    The data is already structured from the policy agent.
    We're just presenting it clearly.
    """

    # --- HEADER ---
    lines = []  # We build the report as a list of lines, then join at the end
                # More efficient than concatenating strings with +=

    lines.append("=" * 60)
    lines.append(f"  {framework} COMPLIANCE AUDIT REPORT")
    lines.append("=" * 60)
    lines.append(f"  URL       : {url}")
    lines.append(f"  Framework : {framework}")
    lines.append(f"  Date      : {datetime.now().strftime('%B %d, %Y %H:%M')}")
    lines.append("=" * 60)

    # --- SCORE ---
    score = audit_result["compliance_score"]

    # Give the score a letter grade and emoji so it reads at a glance
    # This is what catches the judge's eye during a 2-minute demo
    if score >= 90:
        grade, emoji = "A", "🟢"
    elif score >= 70:
        grade, emoji = "B", "🟡"
    elif score >= 50:
        grade, emoji = "C", "🟠"
    else:
        grade, emoji = "F", "🔴"

    lines.append(f"\n  COMPLIANCE SCORE: {score}% ({grade}) {emoji}")
    lines.append(f"  Passed: {audit_result['passed']}/{audit_result['total_checked']} requirements\n")

    # --- VIOLATIONS ---
    violations = audit_result["violations"]

    if not violations:
        lines.append("  ✅ No violations found. This policy appears GDPR compliant.\n")
    else:
        lines.append(f"  VIOLATIONS FOUND: {len(violations)}")
        lines.append("-" * 60)

        for v in violations:
            # Severity badge — HIGH violations are the ones that can get you fined
            severity_icon = {"high": "🔴 HIGH", "medium": "🟡 MEDIUM", "low": "🔵 LOW"}.get(v["severity"], "⚪")

            lines.append(f"\n  [{v['id']}] {v['requirement']}")
            lines.append(f"  Severity : {severity_icon}")
            lines.append(f"  Finding  : {v['explanation']}")

    # --- PASSING REQUIREMENTS ---
    passing = [f for f in audit_result["findings"] if f["satisfied"]]

    lines.append(f"\n{'=' * 60}")
    lines.append(f"  PASSING REQUIREMENTS ({len(passing)})")
    lines.append("-" * 60)

    for p in passing:
        # Truncate evidence to 80 chars so it fits on one line in the terminal
        evidence = p.get("evidence") or "Requirement satisfied"
        if len(evidence) > 80:
            evidence = evidence[:77] + "..."
        lines.append(f"  ✅ [{p['id']}] {p['requirement']}")
        lines.append(f"       Evidence: {evidence}")

    # --- FOOTER ---
    lines.append(f"\n{'=' * 60}")
    lines.append("  Generated by ComplianceAgent — AI Agents Hackathon 2024")
    lines.append("=" * 60)

    # '\n'.join() combines all lines into one string with newlines between them
    return '\n'.join(lines)


if __name__ == "__main__":
    # Test with fake audit data — same shape as what policy_agent returns
    fake_audit = {
        "total_checked": 10,
        "compliance_score": 70,
        "passed": 7,
        "failed": 3,
        "findings": [
            {"id": "A13-1", "satisfied": True,  "requirement": "Identity of data controller",        "evidence": "Acme Corporation, 123 Main St, New York"},
            {"id": "A13-2", "satisfied": False, "requirement": "DPO contact details",                "explanation": "No Data Protection Officer contact found", "severity": "medium"},
            {"id": "A13-3", "satisfied": True,  "requirement": "Purposes and legal basis",            "evidence": "Article 6(1)(b) GDPR — necessary for contract"},
            {"id": "A13-4", "satisfied": True,  "requirement": "Recipients of personal data",         "evidence": "We share with Stripe and Google Analytics"},
            {"id": "A13-5", "satisfied": True,  "requirement": "Data retention period",              "evidence": "We keep your data for 3 years after closure"},
            {"id": "A13-6", "satisfied": True,  "requirement": "Right to access",                    "evidence": "You have the right to access your personal data"},
            {"id": "A13-7", "satisfied": True,  "requirement": "Right to rectification",             "evidence": "You can request correction of inaccurate data"},
            {"id": "A13-8", "satisfied": True,  "requirement": "Right to erasure",                   "evidence": "You may request deletion of your data"},
            {"id": "A13-9", "satisfied": False, "requirement": "Right to withdraw consent",           "explanation": "No mention of withdrawing consent", "severity": "high"},
            {"id": "A13-10","satisfied": False, "requirement": "Right to lodge a complaint",          "explanation": "No supervisory authority mentioned", "severity": "high"},
        ],
        "violations": [
            {"id": "A13-9",  "requirement": "Right to withdraw consent",    "severity": "high",   "explanation": "No mention of withdrawing consent"},
            {"id": "A13-10", "requirement": "Right to lodge a complaint",   "severity": "high",   "explanation": "No supervisory authority mentioned"},
            {"id": "A13-2",  "requirement": "DPO contact details",          "severity": "medium", "explanation": "No Data Protection Officer contact found"},
        ]
    }

    report = generate_report("https://acme.com/privacy", "GDPR", fake_audit)
    print(report)